package io.korostenskyi.chestnut.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006d37)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF69fea1)
val md_theme_light_onPrimaryContainer = Color(0xFF00210c)
val md_theme_light_secondary = Color(0xFF006d41)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF87f9b8)
val md_theme_light_onSecondaryContainer = Color(0xFF002110)
val md_theme_light_tertiary = Color(0xFF6b5e00)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFf8e45c)
val md_theme_light_onTertiaryContainer = Color(0xFF201c00)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdf7)
val md_theme_light_onBackground = Color(0xFF1a1c1a)
val md_theme_light_surface = Color(0xFFfbfdf7)
val md_theme_light_onSurface = Color(0xFF1a1c1a)
val md_theme_light_surfaceVariant = Color(0xFFdde5db)
val md_theme_light_onSurfaceVariant = Color(0xFF414941)
val md_theme_light_outline = Color(0xFF717971)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1ec)
val md_theme_light_inverseSurface = Color(0xFF2e312e)

val md_theme_dark_primary = Color(0xFF48e188)
val md_theme_dark_onPrimary = Color(0xFF00391a)
val md_theme_dark_primaryContainer = Color(0xFF005228)
val md_theme_dark_onPrimaryContainer = Color(0xFF69fea1)
val md_theme_dark_secondary = Color(0xFF69dc9d)
val md_theme_dark_onSecondary = Color(0xFF00391f)
val md_theme_dark_secondaryContainer = Color(0xFF00522f)
val md_theme_dark_onSecondaryContainer = Color(0xFF87f9b8)
val md_theme_dark_tertiary = Color(0xFFdbc842)
val md_theme_dark_onTertiary = Color(0xFF383100)
val md_theme_dark_tertiaryContainer = Color(0xFF514700)
val md_theme_dark_onTertiaryContainer = Color(0xFFf8e45c)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c1a)
val md_theme_dark_onBackground = Color(0xFFe1e3de)
val md_theme_dark_surface = Color(0xFF1a1c1a)
val md_theme_dark_onSurface = Color(0xFFe1e3de)
val md_theme_dark_surfaceVariant = Color(0xFF414941)
val md_theme_dark_onSurfaceVariant = Color(0xFFc0c9bf)
val md_theme_dark_outline = Color(0xFF8b938a)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c1a)
val md_theme_dark_inverseSurface = Color(0xFFe1e3de)

val seed = Color(0xFF33d17a)
val error = Color(0xFFba1b1b)