name: Android General

on:
  push:
    branches:
      - 'feature/*'
      - 'refactor/*'
      - 'fix/*'
      - 'ci/*'
      - 'chore/*'
      - '!build'
      - '!master'

jobs:
  test:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'
      - name: Export debug configuration
        run: echo "TMBD_KEY=$DEBUG_TMBD_KEY" > config/dev.properties
        env:
          DEBUG_TMBD_KEY: ${{ secrets.DEBUG_TMBD_KEY }}
      - name: Build
        run: bash ./gradlew assembleDebug --stacktrace