name: Android Release

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Build Release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Create .signing folder
        run: mkdir .signing
      - name: Decrypt debug keystore
        run: echo "$DEBUG_KEYSTORE_FILE" | base64 -d > .signing/zupa-debug.jks
        env:
          DEBUG_KEYSTORE_FILE:  ${{ secrets.DEBUG_KEYSTORE_FILE }}
      - name: Decrypt release keystore
        run: echo "$RELEASE_KEYSTORE_FILE" | base64 -d > .signing/zupa-release.jks
        env:
          RELEASE_KEYSTORE_FILE: ${{ secrets.RELEASE_KEYSTORE_FILE }}
      - name: Export debug keystore credentials
        run: echo "keyAlias=$DEBUG_KEY_ALIAS" > .signing/debug.properties && echo "storePassword=$DEBUG_STORE_PASSWORD" >> .signing/debug.properties && echo "keyPassword=$DEBUG_KEY_PASSWORD" >> .signing/debug.properties
        env:
          DEBUG_KEY_ALIAS:  ${{ secrets.DEBUG_KEY_ALIAS }}
          DEBUG_STORE_PASSWORD:  ${{ secrets.DEBUG_STORE_PASSWORD }}
          DEBUG_KEY_PASSWORD:  ${{ secrets.DEBUG_KEY_PASSWORD }}
      - name: Export release keystore credentials
        run: echo "keyAlias=$RELEASE_KEY_ALIAS" > .signing/release.properties && echo "storePassword=$RELEASE_STORE_PASSWORD" >> .signing/release.properties && echo "keyPassword=$RELEASE_KEY_PASSWORD" >> .signing/release.properties
        env:
          RELEASE_KEY_ALIAS:  ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_STORE_PASSWORD:  ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_PASSWORD:  ${{ secrets.RELEASE_KEY_PASSWORD }}
      - name: Build
        run: bash ./gradlew assembleProductionRelease --stacktrace