name: Android Release

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'
      - name: Create .signing folder
        run: mkdir .signing
      - name: Decrypt release keystore
        run: echo "$RELEASE_KEYSTORE_FILE" | base64 -d > .signing/release.jks
        env:
          RELEASE_KEYSTORE_FILE: ${{ secrets.RELEASE_KEYSTORE_FILE }}
      - name: Export release configuration
        run: echo "TMBD_KEY=$RELEASE_TMBD_KEY" > config/release.properties
        env:
          RELEASE_TMBD_KEY: ${{ secrets.RELEASE_TMBD_KEY }}
      - name: Export release keystore credentials
        run: echo "keyAlias=$RELEASE_KEY_ALIAS" > .signing/release.properties && echo "storePassword=$RELEASE_STORE_PASSWORD" >> .signing/release.properties && echo "keyPassword=$RELEASE_KEY_PASSWORD" >> .signing/release.properties
        env:
          RELEASE_KEY_ALIAS:  ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_STORE_PASSWORD:  ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_PASSWORD:  ${{ secrets.RELEASE_KEY_PASSWORD }}
      - name: Build
        run: bash ./gradlew bundleRelease --stacktrace
      - name: Upload
        uses: actions/upload-artifact@3
        with:
          name: Build Artifacts
          path: app/build/outputs/